name: CI/CD com Qualidade

on:
 push:
    branches:
      - '**'  
    pull_request:
      branches:
        - '**'  
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Análise SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: Leandro01-oliver_FinanceSportApi
          organization: LeandroX01
          token: bb0469035e9565141b29471f21432f27aa4c787c
          args: >
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
            -Dsonar.qualitygate.wait=true

      - name: Verificar resultado do Quality Gate
        id: quality
        run: |
          if [ "${{ steps.sonar.outputs.quality_gate_status }}" != "PASSED" ]; then
            echo "Quality Gate falhou"
            echo "fail=true" >> $GITHUB_OUTPUT
          else
            echo "Quality Gate passou"
            echo "fail=false" >> $GITHUB_OUTPUT
          fi

      - name: Enviar e-mail se falhar
        if: steps.quality.outputs.fail == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.seuservidor.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "❌ Merge recusado: cobertura de testes insuficiente"
          to: devs@suaprojetotime.com
          from: CI Bot <ci@suaprojetotime.com>
          body: |
            Olá, o merge foi recusado porque o código não atingiu a cobertura mínima de 80%.
            Acesse o relatório do SonarCloud para ver os pontos a melhorar:
            https://sonarcloud.io/project/overview?id=Leandro01-oliver_FinanceSportApi

            Dicas para resolver:
            - Adicione testes unitários para os métodos não cobertos
            - Evite código duplicado e complexidade excessiva
            - Refaça o push após os ajustes

      - name: Merge automático para developp
        if: steps.quality.outputs.fail == 'false'
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: develop
          title: "Merge automático: ${{ github.ref_name }} → develop"
          body: "Merge aprovado automaticamente após passar no quality gate."